[project]
name = "testa"
version = "0.1.1"
description = "Un framework de pruebas para APIs en lenguaje Python."
authors = [
    {name = "Esteban Cossio", email = "esteban.cossio1@udea.edu.co"}
]
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
  "requests >= 2.32.0"
]